### ISSUE TITLE
localhost:3100 not running

### ISSUE THREAD

**Issue by mohitgoyal201617** [pelias/vagrant#44]
I have windows machine and followed steps mentioned https://mapzen.com/blog/pelias-setup-tutorial/. 

https://localhost:9200
===============
{
  "status" : 200,
  "name" : "vagrant-d032c52a",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
    "build_timestamp" : "2015-10-15T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

https://localhost:3100
==================
Not found

**Comment by orangejulius** [comment]
Hey @mohitgoyal201617,
Thanks for reporting this. Can you provide a little bit more information? First of all, can you share the exact command you used to hit our API? I'm presuming it's something like `curl 'http://localhost:3100'`, but I just want to make sure. Can you also share some of the logs for the API server on the vagrant image? Attaching the output of a command like this would be great:

    vagrant@pelias:~$ tail -n 1000 /var/log/pelias-api/current 

Finally, just to make sure the API server is actually running, can you post the output of checking on the pelias-api service? It looks like this: 

    vagrant@pelias:~$ sudo service pelias-api status
    run: pelias-api: (pid 972) 177s; run: log: (pid 970) 177s

**Comment by kujon** [comment]
Hi,

I'm experiencing exactly the same issue, `vagrant up` gets stuck at: `* execute[npm install pelias-api] action run`. There are no logs present and API status doesn't even find the service: `pelias-api: unrecognized service`

**Comment by kujon** [comment]
I managed to get around with with `vagrant reload --provision`, however pelias API seems to have issues finding one of the modules:
```
2016-07-26_12:14:46.34878 Error: Cannot find module 'addressit'
2016-07-26_12:14:46.34878     at Function.Module._resolveFilename (module.js:336:15)
2016-07-26_12:14:46.34878     at Function.Module._load (module.js:278:25)
2016-07-26_12:14:46.34878     at Module.require (module.js:365:17)
2016-07-26_12:14:46.34879     at require (module.js:384:17)
2016-07-26_12:14:46.34879     at Object.<anonymous> (/opt/pelias/pelias-api/node_modules/pelias-text-analyzer/src/parse.js:1:80)
2016-07-26_12:14:46.34879     at Module._compile (module.js:460:26)
2016-07-26_12:14:46.34879     at Object.Module._extensions..js (module.js:478:10)
2016-07-26_12:14:46.34879     at Module.load (module.js:355:32)
2016-07-26_12:14:46.34880     at Function.Module._load (module.js:310:12)
2016-07-26_12:14:46.34880     at Module.require (module.js:365:17)
```

**Comment by orangejulius** [comment]
Hmm, @kujon, I just tried this and didn't get that error. It could have been a temporary issue with git or github, can you try again? `vagrant destroy; vagrant up` is the most surefire way (it will of course get rid of any data you've imported)
